matrix:
  include:
    - language: python
      install:
        - pip install tox
      script:
        - tox
      env:
        - TOXENV=syntax

    - language: shell
      script:
        - bash -c 'shopt -s globstar; shellcheck -x *.sh'

    - language: python
      install:
        - pip install docker-compose==1.24.0
      script:
        - docker-compose --file docker-compose.yml --file docker-compose.latest.yml build --no-cache

    - language: python
      install:
        - pip install docker-compose==1.24.0
      script:
        - docker-compose --file docker-compose.yml --file docker-compose.stable.yml build --no-cache
