version: '3.4'

services:
  arthurd:
    restart: on-failure:5
    image: electrocucaracha/grimoirelab-kingarthur:0.1.15
    build:
      context: ./kingarthur
    depends_on:
      - redis
      - elasticsearch
    command:
      arthurd -c /home/setup.ini
    volumes:
      - ./conf/setup_arthurd.ini:/home/setup.ini:ro
      - ./logs/:/var/log/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/tasks"]
    expose:
      - "8080"
  arthurw:
    image: electrocucaracha/grimoirelab-kingarthur:0.1.15
    build:
      context: ./kingarthur
    depends_on:
      - redis
    command:
      arthurw --debug --database redis://redis/8
    volumes:
      - repos:/tmp/
  redis:
    image: redis:5.0.5
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
  elasticsearch:
    image: bitergia/elasticsearch:6.1.0
    volumes:
      - ./conf/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml:ro
  kibiter:
    restart: on-failure:5
    image: bitergia/kibiter:community-v6.1.4-3
    environment:
      - NODE_OPTIONS=--max-old-space-size=1000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  bestiary:
    image: electrocucaracha/grimoirelab-bestiary
    build:
      context: ./bestiary
  mordred:
    restart: on-failure
    image: electrocucaracha/grimoirelab-sirmordred:0.2.17
    build:
      context: ./sirmordred
    volumes:
      - ./conf/setup_mordred.ini:/sirmordred/conf/setup.cfg:ro
      - ./conf/projects.json:/sirmordred/conf/projects.json:ro
      - ./conf/aliases.json:/sirmordred/conf/aliases.json:ro
      - ./conf/menu.yaml:/sirmordred/conf/menu.yaml:ro
      - ./logs/:/var/log/
      - repos:/root/.perceval/repositories/
      - ./sigils/src/panels/json:/sirmordred/conf/panels/json
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - arthurd
      - redis
      - sortinghat
  sortinghat:
    image: electrocucaracha/grimoirelab-sortinghat:0.7.6
    build:
      context: ./sortinghat
    command:
      sortinghat init grimoirelab
    depends_on:
      - mariadb
    environment:
      SORTINGHAT_DB_HOST: mariadb
      SORTINGHAT_DB_USER: root
      SORTINGHAT_DB_PASSWORD: "${SORTINGHAT_DB_PASSWORD}"
      SORTINGHAT_DB_DATABASE: "${SORTINGHAT_DB_DATABASE}"
      SORTINGHAT_DB_PORT: 3306
  mariadb:
    image: mariadb:10.1.38
    restart: always
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "-p${SORTINGHAT_DB_PASSWORD}", "-e\"SHOW DATABASES;\""]
      interval: 10s
      timeout: 1s
      start_period: 5m
      retries: 5
    environment:
      MYSQL_DATABASE: "${SORTINGHAT_DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${SORTINGHAT_DB_PASSWORD}"
    volumes:
      - ./mariadb-init/sortinghat.sql:/docker-entrypoint-initdb.d/01_sortinghat_ddl.sql:ro
      - ./logs/:/var/log/mysql/

volumes:
  repos:
