---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: '3.4'

services:
  arthurd:
    image: electrocucaracha/grimoirelab-kingarthur:latest
    build:
      context: ./kingarthur
      dockerfile: Dockerfile.latest
  arthurw:
    image: electrocucaracha/grimoirelab-kingarthur:latest
    build:
      context: ./kingarthur
      dockerfile: Dockerfile.latest
  mordred:
    image: electrocucaracha/grimoirelab-sirmordred:latest
    build:
      context: ./sirmordred
      dockerfile: Dockerfile.latest
