---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: '3.4'

services:
  arthurd:
    image: electrocucaracha/grimoirelab-kingarthur:0.1.15
    build:
      context: ./kingarthur
  arthurw:
    image: electrocucaracha/grimoirelab-kingarthur:0.1.15
    build:
      context: ./kingarthur
  mordred:
    image: electrocucaracha/grimoirelab-sirmordred:0.2.20
    build:
      context: ./sirmordred
  sortinghat:
    image: electrocucaracha/grimoirelab-sortinghat:0.7.6
    build:
      context: ./sortinghat
