---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: '3.4'

services:
  arthurd:
    restart: on-failure:5
    image: electrocucaracha/grimoirelab-kingarthur:0.1.15
    depends_on:
      - redis
      - elasticsearch
    command:
      arthurd -c /home/setup.ini
    volumes:
      - ./conf/setup_arthurd.ini:/home/setup.ini:ro
      - ./logs/:/tmp/.arthur/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/tasks"]
    expose:
      - "8080"
  arthurw:
    image: electrocucaracha/grimoirelab-kingarthur:0.1.15
    depends_on:
      - redis
    command:
      arthurw --debug --database redis://redis/8
    volumes:
      - repos:/tmp/
  redis:
    image: redis:5.0.5
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
  elasticsearch:
    image: bitergia/elasticsearch:6.1.0
    volumes:
      - ./conf/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml:ro
  kibiter:
    restart: on-failure:5
    image: bitergia/kibiter:community-v6.1.4-3
    environment:
      - NODE_OPTIONS=--max-old-space-size=1000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  mordred:
    restart: on-failure
    image: electrocucaracha/grimoirelab-sirmordred:0.2.17
    volumes:
      - ./conf/setup_mordred.ini:/sirmordred/conf/setup.cfg:ro
      - ./conf/projects.json:/sirmordred/conf/projects.json:ro
      - ./conf/aliases.json:/sirmordred/conf/aliases.json:ro
      - ./conf/menu.yaml:/sirmordred/conf/menu.yaml:ro
#      - ./sigils/src/panels/json:/sirmordred/conf/panels/json
      - ./conf/git.json:/sirmordred/conf/panels/json/git.json:ro
      - ./logs/:/tmp/log/
      - repos:/root/.perceval/repositories/
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - arthurd
      - redis

volumes:
  repos:
