---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: '3.4'

services:
  arthurd:
    restart: on-failure:5
    image: electrocucaracha/grimoirelab-kingarthur:0.1.18
    depends_on:
      - redis
      - elasticsearch
    command:
      arthurd -c /home/setup.ini
    volumes:
      - ./conf/setup_arthurd.ini:/home/setup.ini:ro
      - ./logs/:/tmp/.arthur/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/tasks"]
    expose:
      - "8080"
  arthurw:
    image: electrocucaracha/grimoirelab-kingarthur:0.1.18
    depends_on:
      - redis
    command:
      arthurw --debug --database redis://redis/8
    volumes:
      - repos:/tmp/
      - /root/.ssh/:/root/.ssh/
  redis:
    image: redis:5.0.5
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
  elasticsearch:
    image: bitergia/elasticsearch:6.1.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml:ro
  elasticsearch_node:
    image: bitergia/elasticsearch:6.1.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.zen.ping.unicast.hosts=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml:ro
  kibiter:
    restart: on-failure:5
    image: bitergia/kibiter:community-v6.1.4-3
    environment:
      - NODE_OPTIONS=--max-old-space-size=1000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  mordred:
    restart: on-failure
    image: electrocucaracha/grimoirelab-sirmordred:0.2.25
    volumes:
      - ./conf/setup_mordred.ini:/sirmordred/conf/setup.cfg:ro
      - ./conf/projects.json:/sirmordred/conf/projects.json:ro
      - ./conf/aliases.json:/sirmordred/conf/aliases.json:ro
      - ./conf/menu.yaml:/sirmordred/conf/menu.yaml:ro
#      - ./sigils/src/panels/json:/sirmordred/conf/panels/json
      - ./conf/git.json:/sirmordred/conf/panels/json/git.json:ro
      - ./logs/:/tmp/log/
      - repos:/root/.perceval/repositories/
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - arthurd
      - redis
      - sortinghat
  sortinghat:
    restart: on-failure
    image: electrocucaracha/grimoirelab-sortinghat:0.7.6
    command:
      sortinghat init ${SORTINGHAT_DB_DATABASE}
    depends_on:
      - mariadb
    environment:
      SORTINGHAT_DB_HOST: mariadb
      SORTINGHAT_DB_USER: root
      SORTINGHAT_DB_PASSWORD: "${SORTINGHAT_DB_PASSWORD}"
      SORTINGHAT_DB_PORT: 3306
  mariadb:
    image: mariadb:10.1.38
    restart: always
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "-p${SORTINGHAT_DB_PASSWORD}", "-e'SHOW DATABASES;'"]
      interval: 5s
      timeout: 1s
      start_period: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "${SORTINGHAT_DB_PASSWORD}"
    volumes:
      - ./mariadb-init/sortinghat.sql:/docker-entrypoint-initdb.d/01_sortinghat_ddl.sql:ro
      - ./logs/:/var/log/mysql/

volumes:
  repos:
  esdata:
