FROM python:3.4
MAINTAINER Victor Morales <electrocucaracha@gmail.com>

RUN pip install git+https://github.com/electrocucaracha/grimoirelab-perceval \
  && pip install --no-cache-dir kingarthur==0.1.15
